### ISSUE TITLE
Can't conda install 0.2.8 with python 3

### ISSUE THREAD

**Issue by danudwary** [kblin/ncbi-genome-download#81] opened 2019-01-05 19:27 UTC
I can't seem to install 0.2.8 in a python 3 env using anaconda. (Pip works without issue)
```
$ conda install -c conda ncbi-genome-download=0.2.8 python=3.6
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - ncbi-genome-download=0.2.8 -> enum34 -> python=2.7
  - python=3.6
Use "conda info <package>" to see the dependencies for each package.

```

**Comment by kblin** [comment] 2019-01-06 08:01
My conda know-how is limited, I don't use it myself. But of course it should not downgrade your python version.
I thought that was sorted by https://github.com/bioconda/bioconda-recipes/blob/master/recipes/ncbi-genome-download/meta.yaml#L33, but there might be some changes in conda regarding how to specify this.

Did this work ok for the 0.2.7 install?

**Comment by druvus** [comment] 2019-01-06 11:56
@danudwary could you please test to install using `conda create -n ngd-test ncbi-genome-download python=3.6`

The version 2.8 of ncbi-genome-download at bioconda is built as noarch so it is independent of python version. However you might have some other incompatible package installed that force the downgrade.

**Comment by jrjhealey** [comment] 2019-01-06 21:38
I don't have an exact answer for the issue, but that line in the yaml file might be part of the problem?

My conda knowledge is also limited, but I do know the `enum34` module is no longer in python3 as it's caused me issues in the past. Is the conda install trying to force the inclusion of the module under python3?

My take home from the conflict message is that python3 is in conflict with ngd 0.2..8 because it requires enum34 which in turn requires python2.x but this is not a strong knowledge area for me.

**Comment by danudwary** [comment] 2019-01-07 17:40
@druvus When I do that, it tries to install ncbi-genome-download 0.2.6. 

Requiring 0.2.7 and python=3.6 fails identically to 0.2.8.

I don't know much about building Anaconda packages, but from the error message it seems that your dependency on enum34, which seems to be incompatible with python3, is the root of the problem.

**Comment by kblin** [comment] 2019-01-08 10:00
Yes, but the `enum34` package is needed for 2.7 builds.

For pip, I can specify which versions of python this dependency applies for: https://github.com/kblin/ncbi-genome-download/blob/master/setup.py#L24
When building `pypi` packages, https://github.com/kblin/ncbi-genome-download/blob/master/setup.cfg#L11 takes care of the same logic.

I thought that line in the bioconda recipe did the same, but apparently it doesn't.

**Comment by druvus** [comment] 2019-01-08 10:15
Bioconda should do the same but the issue is that no conditional dependencies depending on the Python version is allowed for[ noarch packages](https://conda-forge.org/docs/meta.html#building-noarch-packages).  I will rebuild the bioconda package to fix it.

**Comment by kblin** [comment] 2019-01-08 10:19
I hate packaging. 🤦‍♂️ Thanks @druvus

**Comment by druvus** [comment] 2019-01-08 11:55
@danudwary I have rebuild the bioconda package so could you please try to install it again.

**Comment by kblin** [comment] 2019-01-13 06:08
Great! Closing the bug then. 😃

**Closed by kblin** 2019-01-13 06:08 UTC
